services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: flight_itinerary
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "8001:8001"
    env_file:
      - ./server/.env.local
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "8000:8000"
    env_file:
      - ./client/.env.local
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app

volumes:
  postgres_data:
